modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="moreutilities"
version="1.0.01.19.2"
displayName="MoreUtilities"
credits="More Mods, Anton Rosin Dev."
displayURL="https://github.com/MoreMods/MoreUtilities"
authors="More Mods, Anton Rosin Dev."
description='''
Utility mod for Minecraft: Java Edition. Developed by rorosin
'''

[[dependencies.moreutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




