modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="moreutilities"
version="v0-0-beta b1"
displayName="MoreUtilities"
credits="More Mods, Anton Rosin Dev."
displayURL="https://mcreator.net"
authors="More Mods, Anton Rosin Dev."

[[dependencies.moreutilities]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




